// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Author: typeof import('./src/components/Author.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    EnterStarport: typeof import('./src/components/EnterStarport.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Github: typeof import('./src/components/Github.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    QQ: typeof import('./src/components/QQ.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    WeChat: typeof import('./src/components/WeChat.vue')['default']
  }
}
